spring:
   application:
      name: customer-service
server:
   port: ${app_port}
eureka:
   instance:
      metadataMap:
         zone: ${zone_name}
   client:
      serviceURL:
         defaultZone: http://localhost:8900/eureka,http://localhost:8901/eureka
         # EUREKA server in high-availability mode with Eureka – Zone Awareness